version: "3.9"

services:
  database:
    image: postgres:15.5-alpine
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taxi_data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

  
