version: 2

sources:
  - name: staging
    database: learningde 
    schema: taxi_trips_hw

    tables:
      - name: green_trips_non_partitioned
      - name: yellow_trips_non_partitioned
      - name: fhv_trips_non_partitoned
